{
    "items": [
        {   "label": "Archivo Histórico Provincial de Zaragoza",
            "type": "Archivos",
             "index": 1,
             "imageURL": "./AHPZlogo.jpg",
			"imageURL2": "./AHPZlogo2.jpg",
            "texto": " <form action=http://dara.aragon.es/opac/app/results/ method=get target=_blank><input type=hidden value=1 name=ar /><justify><br /> <input type=text name=q size=20 required= /><input value=Buscar type=submit name= /></justify></form> ", 
			"url": "http://dara.aragon.es/opac/app/advanced/ahpz",
			"url2": "http://www.patrimonioculturaldearagon.es/archivo-historico-provincial-de-zaragoza",
			"tipo": [  "1.1 Público", "2.2 Histórico", "3.3 Provincial" ],
			"provincia": [ "Zaragoza" ],
			"comarca": [ "Zaragoza" ],
			"localidad": [ "Zaragoza" ],
            "epoca": [ "0409-1492 Edad Media", "1492-1789 Edad Moderna", "1789- Contemporánea", "1936-1939 Guerra Civil", "1975-1982 Transición", "1978- Democracia", "1982- Autonomía de Aragón" ],
			"recursos": [ "Documentos", "Fotografías", "Carteles", "Pergaminos", "Mapas y planos",  "Audiovisuales",  "Carteles" ]			
        },
       {   "id": "Archivo Histórico Provincial de Zaragoza",
            "birthLatLng": "41.654486, -0.876418"
        },
		{   "label": "Archivo Histórico Provincial de Huesca",
            "type": "Archivos",
             "index": 2,
             "imageURL": "./AHPHlogo.jpg",
			"imageURL2": "./AHPHlogo2.jpg",
            "texto": " <form action=http://dara.aragon.es/opac/app/results/ method=get target=_blank><input type=hidden value=2 name=ar /><justify><br /> <input type=text name=q size=20 required= /><input value=Buscar type=submit name= /></justify></form> ", 
			"url": "http://dara.aragon.es/opac/app/advanced/ahph",
			"url2": "http://www.patrimonioculturaldearagon.es/archivo-historico-provincial-de-huesca",
			"tipo": [  "1.1 Público", "2.2 Histórico", "3.3 Provincial" ],
			"provincia": [ "Huesca" ],
			"comarca": [ "Hoya de Huesca / Plana de Huesca" ],
			"localidad": [ "Huesca" ],
            "epoca": [ "0409-1492 Edad Media", "1492-1789 Edad Moderna", "1936-1939 Guerra Civil", "1789- Contemporánea", "1975-1982 Transición", "1978- Democracia", "1982- Autonomía de Aragón" ],
			"recursos": [ "Documentos", "Fotografías", "Pergaminos", "Mapas y planos", "Audiovisuales", "Carteles" ]			
        },
       {   "id": "Archivo Histórico Provincial de Huesca",
            "birthLatLng": "42.1394624,-0.4053281"
        },
{   "label": "Archivo Histórico Provincial de Teruel",
            "type": "Archivos",
             "index": 3,
             "imageURL": "./AHPTlogo.jpg",
			"imageURL2": "./AHPTlogo2.jpg",
            "texto": " <form action=http://dara.aragon.es/opac/app/results/ method=get target=_blank><input type=hidden value=3 name=ar /><justify><br /> <input type=text name=q size=20 required= /><input value=Buscar type=submit name= /></justify></form> ", 
			"url": "http://dara.aragon.es/opac/app/advanced/ahpt",
			"url2": "http://www.patrimonioculturaldearagon.es/archivo-historico-provincial-de-teruel",
			"tipo": [ "1.1 Público", "2.2 Histórico", "3.3 Provincial" ],
			"provincia": [ "Teruel" ],
			"comarca": [ "Comunidad de Teruel" ],
			"localidad": [ "Teruel" ],
            "epoca": [ "0409-1492 Edad Media", "1492-1789 Edad Moderna", "1936-1939 Guerra Civil", "1789- Contemporánea", "1975-1982 Transición", "1978- Democracia", "1982- Autonomía de Aragón" ],
			"recursos": [ "Documentos", "Fotografías", "Pergaminos", "Mapas y planos", "Audiovisuales", "Carteles" ]			
        },
       {   "id": "Archivo Histórico Provincial de Teruel",
            "birthLatLng": "40.3448195,-1.105149"
        },		
{   "label": "Archivo de la Administración de la Comunidad Autónoma de Aragón",
            "type": "Archivos",
             "index": 4,
             "imageURL": "./AACAAlogo.jpg",
			"imageURL2": "./AACAAlogo2.jpg",
            "texto": " <form action=http://dara.aragon.es/opac/app/results/ method=get target=_blank><input type=hidden value=21 name=ar /><justify><br /> <input type=text name=q size=20 required= /><input value=Buscar type=submit name= /></justify></form> ", 
			"url": "http://dara.aragon.es/opac/app/advanced/aacaa",
			"url2": "http://www.aragon.es/archivo",
			"tipo": [ "1.1 Público", "2.1 Administrativo", "3.1 Autonómico" ],
			"provincia": [ "Zaragoza" ],
			"comarca": [ "Zaragoza" ],
			"localidad": [ "Zaragoza" ],
            "epoca": [ "1978- Democracia",  "1975-1982 Transición", "1982- Autonomía de Aragón" ],
			"recursos": [ "Documentos", "Fotografías", "Mapas y planos" ]			
        },
       {   "id": "Archivo de la Administración de la Comunidad Autónoma de Aragón",
            "birthLatLng": "41.653145, -0.891808"
        },
{   "label": "Archivo Municipal de Ansó",
            "type": "Archivos",
             "index": 5,
             "imageURL": "./ANSOlogo.jpg",
			"imageURL2": "./ANSOlogo2.jpg",
            "texto": " <form action=http://dara.aragon.es/opac/app/results/aman method=get target=_blank><input type=hidden /><justify><br /> <input type=text name=q size=20 required= /><input value=Buscar type=submit name= /></justify></form> ", 
			"url": "http://dara.aragon.es/opac/app/advanced/aman",
			"url2": "http://www.anso.es/",
			"tipo": [ "1.1 Público", "2.1 Administrativo", "2.2 Histórico", "3.2 Municipal y comarcal" ],
			"provincia": [ "Huesca" ],
			"comarca": [ "La Jacetania" ],
			"localidad": [ "Ansó" ],
            "epoca": [ "1789- Contemporánea"],
			"recursos": [ "Documentos", "Pergaminos" ]			
        },
       {   "id": "Archivo Municipal de Ansó",
            "birthLatLng": "42.7556515,-0.8275432"
        },
{   "label": "Archivo Municipal de La Puebla de Alfindén",
            "type": "Archivos",
             "index": 6,
             "imageURL": "./APALlogo.jpg",
			"imageURL2": "./APALlogo2.jpg",
            "texto": " <form action=http://dara.aragon.es/opac/app/results/ampa method=get target=_blank><input type=hidden /><justify><br /> <input type=text name=q size=20 required= /><input value=Buscar type=submit name= /></justify></form> ", 
			"url": "http://dara.aragon.es/opac/app/advanced/ampa",
			"url2": "http://www.lapuebladealfinden.es/",
			"tipo": [ "1.1 Público", "2.1 Administrativo", "2.2 Histórico", "3.2 Municipal y comarcal" ],
			"provincia": [ "Zaragoza" ],
			"comarca": [ "Zaragoza" ],
			"localidad": [ "La Puebla de Alfindén" ],
            "epoca": [ "1789- Contemporánea"],
			"recursos": [ "Documentos", "Pergaminos" ]			
        },
       {   "id": "Archivo Municipal de La Puebla de Alfindén",
            "birthLatLng": "41.6319235,-0.7511062"
        },
{   "label": "Comarca del Maestrazgo",
            "type": "Archivos",
             "index": 7,
             "imageURL": "./COMA1logo.jpg",
			"imageURL2": "./COMAlogo2.jpg",
            "texto": " <form action=http://dara.aragon.es/opac/app/results/coma method=get target=_blank><input type=hidden /><justify><br /> <input type=text name=q size=20 required= /><input value=Buscar type=submit name= /></justify></form> ", 
			"url": "http://dara.aragon.es/opac/app/advanced/coma",
			"url2": "http://www.comarcamaestrazgo.es",
			"tipo": [ "1.1 Público", "2.1 Administrativo", "3.2 Municipal y comarcal" ],
			"provincia": [ "Teruel" ],
			"comarca": [ "Maestrazgo" ],
			"localidad": [ "Cantavieja" ],
            "epoca": ["1789- Contemporánea"],
			"recursos": [ "Documentos"]			
        },
       {   "id": "Comarca del Maestrazgo",
            "birthLatLng": "40.5247912,-0.4051754"
        },
{   "label": "Archivo Municipal de Cantavieja",
            "type": "Archivos",
             "index": 8,
             "imageURL": "./COMA2logo.jpg",
			"imageURL2": "./COMAlogo3.jpg",
            "texto": " <form action=http://dara.aragon.es/opac/app/results/ method=get target=_blank><input type=hidden value=23 name=ar /><justify><br /> <input type=text name=q size=20 required= /><input value=Buscar type=submit name= /></justify></form> ", 
			"url": "http://dara.aragon.es/opac/app/advanced/",
			"url2": "http://www.cantavieja.es/",
			"tipo": [ "1.1 Público", "2.1 Administrativo", "2.2 Histórico", "3.2 Municipal y comarcal" ],
			"provincia": [ "Teruel" ],
			"comarca": [ "Maestrazgo" ],
			"localidad": [ "Cantavieja" ],
            "epoca": [ "1789- Contemporánea"],
			"recursos": [ "Documentos", "Pergaminos" ]			
        },
       {   "id": "Archivo Municipal de Cantavieja",
            "birthLatLng": "40.5280412,-0.4056862"
        },
{   "label": "Casa de Ganaderos",
            "type": "Archivos",
             "index": 9,
             "imageURL": "./AFCGlogo.jpg",
			"imageURL2": "./AFCGlogo2.jpg",
            "texto": " <form action=http://dara.aragon.es/opac/app/results/afcg method=get target=_blank><input type=hidden /><justify><br /> <input type=text name=q size=20 required= /><input value=Buscar type=submit name= /></justify></form> ", 
			"url": "http://dara.aragon.es/opac/app/advanced/afcg",
			"url2": "http://www.casaganaderos.com/",
			"tipo": [ "1.2 Privado", "2.2 Histórico" ],
			"provincia": [ "Zaragoza" ],
			"comarca": [ "Zaragoza" ],
			"localidad": [ "Zaragoza" ],
            "epoca": [ "0409-1492 Edad Media", "1492-1789 Edad Moderna" ],
			"recursos": [ "Documentos", "Pergaminos" ]			
        },
       {   "id": "Casa de Ganaderos",
            "birthLatLng": "41.652581, -0.878415"
        },
{   "label": "Archivo Municipal de Abiego",
            "type": "Archivos",
             "index": 10,
             "imageURL": "./SOMOlogo.jpg",
			"imageURL2": "./ABIElogo.jpg",
            "texto": " <form action=http://dara.aragon.es/opac/app/results/ method=get target=_blank><input type=hidden value=14 name=ar /><justify><br /> <input type=text name=q size=20 required= /><input value=Buscar type=submit name= /></justify></form> ", 
			"url": "http://dara.aragon.es/opac/app/advanced/",
			"url2": "http://www.abiego.es",
			"tipo": [ "1.1 Público", "2.1 Administrativo", "2.2 Histórico", "3.2 Municipal y comarcal" ],
			"provincia": [ "Huesca" ],
			"comarca": [ "Somontano de Barbastro" ],
			"localidad": [ "Abiego" ],
            "epoca": [ "1789- Contemporánea"],
			"recursos": [ "Documentos", "Pergaminos" ]			
        },
       {   "id": "Archivo Municipal de Abiego",
            "birthLatLng": "42.1218259,-0.0711381"
        },
{   "label": "Archivo Municipal de Fontanete",
            "type": "Archivos",
             "index": 11,
             "imageURL": "./COMA3logo.jpg",
			"imageURL2": "./FONTlogo.jpg",
            "texto": " <form action=http://dara.aragon.es/opac/app/results/ method=get target=_blank><input type=hidden value=17 name=ar /><justify><br /> <input type=text name=q size=20 required= /><input value=Buscar type=submit name= /></justify></form> ", 
			"url": "http://dara.aragon.es/opac/app/advanced/",
			"url2": "http://www.fortanete.net/",
			"tipo": [ "1.1 Público", "2.1 Administrativo", "2.2 Histórico", "3.2 Municipal y comarcal" ],
			"provincia": [ "Teruel" ],
			"comarca": [ "Maestrazgo" ],
			"localidad": [ "Fontanete" ],
            "epoca": [ "1789- Contemporánea"],
			"recursos": [ "Documentos", "Pergaminos" ]			
        },
       {   "id": "Archivo Municipal de Fontanete",
            "birthLatLng": "40.5053508,-0.5226589"
        },
{   "label": "Archivo Municipal de Jaca",
            "type": "Archivos",
             "index": 12,
             "imageURL": "./AMJAlogo.jpg",
			"imageURL2": "./AMJAlogo2.jpg",
            "texto": " <form action=http://dara.aragon.es/opac/app/results/ method=get target=_blank><input type=hidden value=19 name=ar /><justify><br /> <input type=text name=q size=20 required= /><input value=Buscar type=submit name= /></justify></form> ", 
			"url": "http://dara.aragon.es/opac/app/advanced/amja",
			"url2": "http://www.jaca.es/",
			"tipo": [ "1.1 Público", "2.1 Administrativo", "2.2 Histórico", "3.2 Municipal y comarcal" ],
			"provincia": [ "Huesca" ],
			"comarca": [ "La Jacetania" ],
			"localidad": [ "Jaca" ],
            "epoca": [ "0409-1492 Edad Media", "1492-1789 Edad Moderna", "1789- Contemporánea"],
			"recursos": [ "Documentos", "Pergaminos" ]			
        },
       {   "id": "Archivo Municipal de Jaca",
            "birthLatLng": "42.568562, -0.550675"
        },
{   "label": "Archivo Municipal de La Cuba",
            "type": "Archivos",
             "index": 13,
             "imageURL": "./COMA4logo.jpg",
			"imageURL2": "./CUBAlogo.jpg",
            "texto": " <form action=http://dara.aragon.es/opac/app/results/ method=get target=_blank><input type=hidden value=16 name=ar /><justify><br /> <input type=text name=q size=20 required= /><input value=Buscar type=submit name= /></justify></form> ", 
			"url": "http://dara.aragon.es/opac/app/advanced/",
			"url2": "http://www.lacuba.es/",
			"tipo": [ "1.1 Público", "2.1 Administrativo", "2.2 Histórico", "3.2 Municipal y comarcal" ],
			"provincia": [ "Teruel" ],
			"comarca": [ "Maestrazgo" ],
			"localidad": [ "La Cuba" ],
            "epoca": [ "1789- Contemporánea"],
			"recursos": [ "Documentos", "Pergaminos" ]			
        },
       {   "id": "Archivo Municipal de La Cuba",
            "birthLatLng": "40.5913795,-0.2973829"
        },
{   "label": "Archivo Municipal de Mirambel",
            "type": "Archivos",
             "index": 14,
             "imageURL": "./COMA5logo.jpg",
			"imageURL2": "./MIRAlogo2.jpg",
            "texto": " <form action=http://dara.aragon.es/opac/app/results/ method=get target=_blank><input type=hidden value=12 name=ar /><justify><br /> <input type=text name=q size=20 required= /><input value=Buscar type=submit name= /></justify></form> ", 
			"url": "http://dara.aragon.es/opac/app/advanced/",
			"url2": "http://www.mirambel.es/",
			"tipo": [ "1.1 Público", "2.1 Administrativo", "2.2 Histórico", "3.2 Municipal y comarcal" ],
			"provincia": [ "Teruel" ],
			"comarca": [ "Maestrazgo" ],
			"localidad": [ "Mirambel" ],
            "epoca": [ "1789- Contemporánea"],
			"recursos": [ "Documentos", "Pergaminos" ]			
        },
       {   "id": "Archivo Municipal de Mirambel",
            "birthLatLng": "40.5878383,-0.3418601"
        },
{   "label": "Archivo Municipal de Olvena",
            "type": "Archivos",
             "index": 15,
             "imageURL": "./SOMO2logo.jpg",
			"imageURL2": "./OLVElogo2.jpg",
            "texto": " <form action=http://dara.aragon.es/opac/app/results/ method=get target=_blank><input type=hidden value=15 name=ar /><justify><br /> <input type=text name=q size=20 required= /><input value=Buscar type=submit name= /></justify></form> ", 
			"url": "http://dara.aragon.es/opac/app/advanced/",
			"url2": "http://www.dphuesca.es/index.php/mod.entidades/mem.detalle/identidad.128/relcategoria.205/chk.df7cfaf522999e26809db85ea437c8dc.html",
			"tipo": [ "1.1 Público", "2.1 Administrativo", "2.2 Histórico", "3.2 Municipal y comarcal" ],
			"provincia": [ "Huesca" ],
			"comarca": [ "Somontano de Barbastro" ],
			"localidad": [ "Olvena" ],
            "epoca": [ "1789- Contemporánea"],
			"recursos": [ "Documentos" ]			
        },
       {   "id": "Archivo Municipal de Olvena",
            "birthLatLng": "42.1067924,0.2596425"
        },
{   "label": "Archivo Parroquial de Fonz",
            "type": "Archivos",
             "index": 16,
             "imageURL": "./PFONlogo.jpg",
			"imageURL2": "./PFONlogo.jpg",
            "texto": " <form action=http://dara.aragon.es/opac/app/results/ method=get target=_blank><input type=hidden value=10 name=ar /><justify><br /> <input type=text name=q size=20 required= /><input value=Buscar type=submit name= /></justify></form> ", 
			"url": "http://dara.aragon.es/opac/app/advanced/",
			"url2": "http://www.diocesisbarbastromonzon.org",
			"tipo": [ "1.2 Privado", "2.2 Histórico", "4.1 Religioso" ],
			"provincia": [ "Huesca" ],
			"comarca": [ "Cinca Medio" ],
			"localidad": [ "Fonz" ],
            "epoca": [ "1492-1789 Edad Moderna", "1789- Contemporánea"],
			"recursos": [ "Documentos" ]			
        },
       {   "id": "Archivo Parroquial de Fonz",
            "birthLatLng": "42.0103987,0.2578969"
        },
	{   "label": "Archivo de la Fundación Bernardo Aladrén",
            "type": "Archivos",
             "index": 17,
             "imageURL": "./AFBAlogo.jpg",
			"imageURL2": "./AFBAlogo2.jpg",
            "texto": " <form action=http://dara.aragon.es/opac/app/results/ method=get target=_blank><input type=hidden value=20 name=ar /><justify><br /> <input type=text name=q size=20 required= /><input value=Buscar type=submit name= /></justify></form> ", 
			"url": "http://dara.aragon.es/opac/app/advanced/afba",
			"url2": "http://fundacionaladren.com/",
			"tipo": [ "1.2 Privado", "2.2 Histórico", "4.4 Sindical" ],
			"provincia": [ "Zaragoza" ],
			"comarca": [ "Zaragoza" ],
			"localidad": [ "Zaragoza" ],
            "epoca": [ "1975-1982 Transición", "1978- Democracia" ],
			"recursos": [ "Documentos" ]			
        },
       {   "id": "Archivo de la Fundación Bernardo Aladrén",
            "birthLatLng": "41.6656496,-0.8916303"
        },
{   "label": "Archivo Municipal de Adahuesca",
            "type": "Archivos",
             "index": 18,
             "imageURL": "./ADAHlogo.jpg",
			"imageURL2": "./ADAHlogo2.jpg",
            "texto": " <form action=http://dara.aragon.es/opac/app/results/ method=get target=_blank><input type=hidden value=59 name=ar /><justify><br /> <input type=text name=q size=20 required= /><input value=Buscar type=submit name= /></justify></form> ", 
			"url": "http://dara.aragon.es/opac/app/advanced/",
			"url2": "http://www.adahuesca.es/",
			"tipo": [ "1.1 Público", "2.1 Administrativo", "2.2 Histórico", "3.2 Municipal y comarcal" ],
			"provincia": [ "Huesca" ],
			"comarca": [ "Somontano de Barbastro" ],
			"localidad": [ "Adahuesca" ],
            "epoca": [ "0409-1492 Edad Media", "1789- Contemporánea" ],
			"recursos": [ "Documentos", "Pergaminos" ]			
        },
       {   "id": "Archivo Municipal de Adahuesca",
            "birthLatLng": "42.1461527,-0.0083452"
        },
{   "label": "Archivo Municipal de Ainzón",
            "type": "Archivos",
             "index": 19,
             "imageURL": "./AINZlogo.jpg",
			"imageURL2": "./AINZlogo.jpg",
            "texto": " <form action=http://dara.aragon.es/opac/app/results/ method=get target=_blank><input type=hidden value=45 name=ar /><justify><br /> <input type=text name=q size=20 required= /><input value=Buscar type=submit name= /></justify></form> ", 
			"url": "http://dara.aragon.es/opac/app/advanced/",
			"url2": "http://www.dpz.es/municipio/municipios/ainzon",
			"tipo": [ "1.1 Público", "2.1 Administrativo", "2.2 Histórico", "3.2 Municipal y comarcal" ],
			"provincia": [ "Zaragoza" ],
			"comarca": [ "Campo de Borja" ],
			"localidad": [ "Ainzón" ],
            "epoca": [ "1789- Contemporánea" ],
			"recursos": [ "Documentos" ]			
        },
       {   "id": "Archivo Municipal de Ainzón",
            "birthLatLng": "41.8170422,-1.5201242"
        },
{   "label": "Archivo Municipal de Albarracín",
            "type": "Archivos",
             "index": 20,
             "imageURL": "./ALBAlogo.jpg",
			"imageURL2": "./ALBAlogo2.jpg",
            "texto": " <form action=http://dara.aragon.es/opac/app/results/ method=get target=_blank><input type=hidden value=51 name=ar /><justify><br /> <input type=text name=q size=20 required= /><input value=Buscar type=submit name= /></justify></form> ", 
			"url": "http://dara.aragon.es/opac/app/advanced/",
			"url2": "http://www.albarracin.es/",
			"tipo": [ "1.1 Público", "2.1 Administrativo", "2.2 Histórico", "3.2 Municipal y comarcal" ],
			"provincia": [ "Teruel" ],
			"comarca": [ "Sierra de Albarracín" ],
			"localidad": [ "Albarracín" ],
            "epoca": [ "1492-1789 Edad Moderna", "1789- Contemporánea"],
			"recursos": [ "Documentos", "Pergaminos" ]			
        },
       {   "id": "Archivo Municipal de Albarracín",
            "birthLatLng": "40.407587,-1.4433779"
        },
{   "label": "Ayuntamiento de Alcañiz",
            "type": "Archivos",
             "index": 21,
             "imageURL": "./ALCAlogo.jpg",
			"imageURL2": "./ALCAlogo.jpg",
            "texto": " <form action=http://dara.aragon.es/opac/app/results/ method=get target=_blank><input type=hidden value=53 name=ar /><justify><br /> <input type=text name=q size=20 required= /><input value=Buscar type=submit name= /></justify></form> ", 
			"url": "http://dara.aragon.es/opac/app/advanced/",
			"url2": "https://www.alcaniz.es/",
			"tipo": [ "1.1 Público", "2.1 Administrativo", "2.2 Histórico", "3.2 Municipal y comarcal" ],
			"provincia": [ "Teruel" ],
			"comarca": [ "Bajo Aragón" ],
			"localidad": [ "Alcañiz" ],
            "epoca": [ "1492-1789 Edad Moderna", "1789- Contemporánea"],
			"recursos": [ "Documentos", "Pergaminos" ]			
        },
       {   "id": "Ayuntamiento de Alcañiz",
            "birthLatLng": "41.050487,-0.1324447"
        },
{   "label": "Ayuntamiento de Allepuz",
            "type": "Archivos",
             "index": 22,
             "imageURL": "./ALLElogo.jpg",
			"imageURL2": "./ALLElogo.jpg",
            "texto": " <form action=http://dara.aragon.es/opac/app/results/ method=get target=_blank><input type=hidden value=60 name=ar /><justify><br /> <input type=text name=q size=20 required= /><input value=Buscar type=submit name= /></justify></form> ", 
			"url": "http://dara.aragon.es/opac/app/advanced/",
			"url2": "http://www.allepuz.es/",
			"tipo": [ "1.1 Público", "2.1 Administrativo", "2.2 Histórico", "3.2 Municipal y comarcal" ],
			"provincia": [ "Teruel" ],
			"comarca": [ "Maestrazgo" ],
			"localidad": [ "Allepuz" ],
            "epoca": [ "1492-1789 Edad Moderna", "1789- Contemporánea"],
			"recursos": [ "Documentos" ]			
        },
       {   "id": "Ayuntamiento de Allepuz",
            "birthLatLng": "40.4923203,-0.7278828"
        },
{   "label": "Ayuntamiento de Almudevar",
            "type": "Archivos",
             "index": 23,
             "imageURL": "./ALMUlogo.jpg",
			"imageURL2": "./ALMUlogo2.jpg",
            "texto": " <form action=http://dara.aragon.es/opac/app/results/ method=get target=_blank><input type=hidden value=38 name=ar /><justify><br /> <input type=text name=q size=20 required= /><input value=Buscar type=submit name= /></justify></form> ", 
			"url": "http://dara.aragon.es/opac/app/advanced/",
			"url2": "http://www.almudevar.es/",
			"tipo": [ "1.1 Público", "2.1 Administrativo", "2.2 Histórico", "3.2 Municipal y comarcal" ],
			"provincia": [ "Huesca" ],
			"comarca": [ "Hoya de Huesca / Plana de Huesca" ],
			"localidad": [ "Almudevar" ],
            "epoca": [ "0409-1492 Edad Media", "1492-1789 Edad Moderna", "1789- Contemporánea"],
			"recursos": [ "Documentos" ]			
        },
       {   "id": "Ayuntamiento de Almudevar",
            "birthLatLng": "42.042943,-0.5831147"
        },
{   "label": "Ayuntamiento de Alquezar",
            "type": "Archivos",
             "index": 24,
             "imageURL": "./ALQUlogo.jpg",
			"imageURL2": "./ALQUlogo2.jpg",
            "texto": " <form action=http://dara.aragon.es/opac/app/results/ method=get target=_blank><input type=hidden value=30 name=ar /><justify><br /> <input type=text name=q size=20 required= /><input value=Buscar type=submit name= /></justify></form> ", 
			"url": "http://dara.aragon.es/opac/app/advanced/",
			"url2": "http://www.alquezar.es/",
			"tipo": [ "1.1 Público", "2.1 Administrativo", "2.2 Histórico", "3.2 Municipal y comarcal" ],
			"provincia": [ "Huesca" ],
			"comarca": [ "Somontano de Barbastro" ],
			"localidad": [ "Alquezar" ],
            "epoca": [ "0409-1492 Edad Media", "1492-1789 Edad Moderna", "1789- Contemporánea"],
			"recursos": [ "Documentos" ]			
        },
       {   "id": "Ayuntamiento de Alquezar",
            "birthLatLng": "42.1728015,-0.0045921"
        },
{   "label": "Ayuntamiento de Barbastro",
            "type": "Archivos",
             "index": 25,
             "imageURL": "./BARBlogo.jpg",
			"imageURL2": "./BARBlogo2.jpg",
            "texto": " <form action=http://dara.aragon.es/opac/app/results/ method=get target=_blank><input type=hidden value=37 name=ar /><justify><br /> <input type=text name=q size=20 required= /><input value=Buscar type=submit name= /></justify></form> ", 
			"url": "http://dara.aragon.es/opac/app/advanced/",
			"url2": "http://www.barbastro.org/",
			"tipo": [ "1.1 Público", "2.1 Administrativo", "2.2 Histórico", "3.2 Municipal y comarcal" ],
			"provincia": [ "Huesca" ],
			"comarca": [ "Somontano de Barbastro" ],
			"localidad": [ "Barbastro" ],
            "epoca": [ "0409-1492 Edad Media", "1492-1789 Edad Moderna", "1789- Contemporánea"],
			"recursos": [ "Documentos" ]			
        },
       {   "id": "Ayuntamiento de Barbastro",
            "birthLatLng": "42.0368928,0.1234702"
        },
{   "label": "Archivo del Ayuntamiento de Borja",
            "type": "Archivos",
             "index": 26,
             "imageURL": "./BORJlogo.jpg",
			"imageURL2": "./BORJlogo2.jpg",
            "texto": " <form action=http://dara.aragon.es/opac/app/results/ method=get target=_blank><input type=hidden value=46 name=ar /><justify><br /> <input type=text name=q size=20 required= /><input value=Buscar type=submit name= /></justify></form> ", 
			"url": "http://dara.aragon.es/opac/app/advanced/",
			"url2": "http://www.borja.es",
			"tipo": [ "1.1 Público", "2.1 Administrativo", "2.2 Histórico", "3.2 Municipal y comarcal" ],
			"provincia": [ "Zaragoza" ],
			"comarca": [ "Campo de Borja" ],
			"localidad": [ "Borja" ],
            "epoca": [ "1789- Contemporánea" ],
			"recursos": [ "Documentos" ]			
        },
       {   "id": "Archivo del Ayuntamiento de Borja",
            "birthLatLng": "41.834223,-1.532936"
        },
{   "label": "Ayuntamiento de Calaceite",
            "type": "Archivos",
             "index": 27,
             "imageURL": "./CALAlogo.jpg",
			"imageURL2": "./CALAlogo2.jpg",
            "texto": " <form action=http://dara.aragon.es/opac/app/results/ method=get target=_blank><input type=hidden value=42 name=ar /><justify><br /> <input type=text name=q size=20 required= /><input value=Buscar type=submit name= /></justify></form> ", 
			"url": "http://dara.aragon.es/opac/app/advanced/",
			"url2": "http://www.calaceite.es/",
			"tipo": [ "1.1 Público", "2.1 Administrativo", "2.2 Histórico", "3.2 Municipal y comarcal" ],
			"provincia": [ "Teruel" ],
			"comarca": [ "Matarraña / Matarranya" ],
			"localidad": [ "Calaceite" ],
            "epoca": [ "1492-1789 Edad Moderna", "1789- Contemporánea"],
			"recursos": [ "Documentos" ]			
        },
       {   "id": "Ayuntamiento de Calaceite",
            "birthLatLng": "41.0174373,0.1883706"
        },
{   "label": "Ayuntamiento de Calatayud",
            "type": "Archivos",
             "index": 28,
             "imageURL": "./CALATlogo.jpg",
			"imageURL2": "./CALATlogo2.jpg",
            "texto": " <form action=http://dara.aragon.es/opac/app/results/ method=get target=_blank><input type=hidden value=54 name=ar /><justify><br /> <input type=text name=q size=20 required= /><input value=Buscar type=submit name= /></justify></form> ", 
			"url": "http://dara.aragon.es/opac/app/advanced/",
			"url2": "http://www.calatayud.es/",
			"tipo": [ "1.1 Público", "2.1 Administrativo", "2.2 Histórico", "3.2 Municipal y comarcal" ],
			"provincia": [ "Zaragoza" ],
			"comarca": [ "Comunidad de Calatayud" ],
			"localidad": [ "Calatayud" ],
            "epoca": [ "1789- Contemporánea"],
			"recursos": [ "Documentos" ]			
        },
       {   "id": "Ayuntamiento de Calatayud",
            "birthLatLng": "41.3532174,-1.6419887"
        },
{   "label": "Ayuntamiento de Cañada de Benatanduz",
            "type": "Archivos",
             "index": 29,
             "imageURL": "./CANABlogo.jpg",
			"imageURL2": "./CANABlogo2.jpg",
            "texto": " <form action=http://dara.aragon.es/opac/app/results/ method=get target=_blank><input type=hidden value=61 name=ar /><justify><br /> <input type=text name=q size=20 required= /><input value=Buscar type=submit name= /></justify></form> ", 
			"url": "http://dara.aragon.es/opac/app/advanced/",
			"url2": "http://www.canadadebenatanduz.es/",
			"tipo": [ "1.1 Público", "2.1 Administrativo", "2.2 Histórico", "3.2 Municipal y comarcal" ],
			"provincia": [ "Teruel" ],
			"comarca": [ "Maestrazgo" ],
			"localidad": [ "Cañada de Benatanduz" ],
            "epoca": [ "1789- Contemporánea" ],
			"recursos": [ "Documentos" ]			
        },
       {   "id": "Ayuntamiento de Cañada de Benatanduz",
            "birthLatLng": "40.5784794,-0.5371016"
        },
{   "label": "Ayuntamiento de Castejón del Puente",
            "type": "Archivos",
             "index": 30,
             "imageURL": "./CASTEJlogo.jpg",
			"imageURL2": "./CASTEJlogo2.jpg",
            "texto": " <form action=http://dara.aragon.es/opac/app/results/ method=get target=_blank><input type=hidden value=35 name=ar /><justify><br /> <input type=text name=q size=20 required= /><input value=Buscar type=submit name= /></justify></form> ", 
			"url": "http://dara.aragon.es/opac/app/advanced/",
			"url2": "http://www.castejondelpuente.es/",
			"tipo": [ "1.1 Público", "2.1 Administrativo", "2.2 Histórico", "3.2 Municipal y comarcal" ],
			"provincia": [ "Huesca" ],
			"comarca": [ "Somontano de Barbastro" ],
			"localidad": [ "Castejón del Puente" ],
            "epoca": [  "1789- Contemporánea"],
			"recursos": [ "Documentos" ]			
        },
       {   "id": "Ayuntamiento de Castejón del Puente",
            "birthLatLng": "41.9620138,0.1595908"
        },
{   "label": "Ayuntamiento de Castillazuelo",
            "type": "Archivos",
             "index": 31,
             "imageURL": "./CASTIlogo.jpg",
			"imageURL2": "./CASTIlogo2.jpg",
            "texto": " <form action=http://dara.aragon.es/opac/app/results/ method=get target=_blank><input type=hidden value=33 name=ar /><justify><br /> <input type=text name=q size=20 required= /><input value=Buscar type=submit name= /></justify></form> ", 
			"url": "http://dara.aragon.es/opac/app/advanced/",
			"url2": "http://www.castillazuelo.es/",
			"tipo": [ "1.1 Público", "2.1 Administrativo", "2.2 Histórico", "3.2 Municipal y comarcal" ],
			"provincia": [ "Huesca" ],
			"comarca": [ "Somontano de Barbastro" ],
			"localidad": [ "Castillazuelo" ],
            "epoca": [  "1789- Contemporánea"],
			"recursos": [ "Documentos" ]			
        },
       {   "id": "Ayuntamiento de Castillazuelo",
            "birthLatLng": "42.068459, 0.064709"
        },
{   "label": "Ayuntamiento de Daroca",
            "type": "Archivos",
             "index": 32,
             "imageURL": "./DAROlogo.jpg",
			"imageURL2": "./DAROlogo2.jpg",
            "texto": " <form action=http://dara.aragon.es/opac/app/results/ method=get target=_blank><input type=hidden value=48 name=ar /><justify><br /> <input type=text name=q size=20 required= /><input value=Buscar type=submit name= /></justify></form> ", 
			"url": "http://dara.aragon.es/opac/app/advanced/",
			"url2": "http://www.daroca.es/",
			"tipo": [ "1.1 Público", "2.1 Administrativo", "2.2 Histórico", "3.2 Municipal y comarcal" ],
			"provincia": [ "Zaragoza" ],
			"comarca": [ "Campo de Daroca" ],
			"localidad": [ "Daroca" ],
            "epoca": [ "1789- Contemporánea"],
			"recursos": [ "Documentos" ]			
        },
       {   "id": "Ayuntamiento de Daroca",
            "birthLatLng": "41.1145446,-1.4144349"
        },
{   "label": "Ayuntamiento de Ejea de los Caballeros",
            "type": "Archivos",
             "index": 33,
             "imageURL": "./EJEAlogo.jpg",
			"imageURL2": "./EJEAlogo2.jpg",
            "texto": " <form action=http://dara.aragon.es/opac/app/results/ method=get target=_blank><input type=hidden value=49 name=ar /><justify><br /> <input type=text name=q size=20 required= /><input value=Buscar type=submit name= /></justify></form> ", 
			"url": "http://dara.aragon.es/opac/app/advanced/",
			"url2": "http://www.ejea.es/",
			"tipo": [ "1.1 Público", "2.1 Administrativo", "2.2 Histórico", "3.2 Municipal y comarcal" ],
			"provincia": [ "Zaragoza" ],
			"comarca": [ "Cinco Villas" ],
			"localidad": [ "Ejea de los Caballeros" ],
            "epoca": [ "1789- Contemporánea"],
			"recursos": [ "Documentos" ]			
        },
       {   "id": "Ayuntamiento de Ejea de los Caballeros",
            "birthLatLng": "42.1267885,-1.1386085"
        },
{   "label": "Ayuntamiento de El Grado/Lo Grau",
            "type": "Archivos",
             "index": 34,
             "imageURL": "./SOMO4logo.jpg",
			"imageURL2": "./GRADOlogo.jpg",
            "texto": " <form action=http://dara.aragon.es/opac/app/results/ method=get target=_blank><input type=hidden value=34 name=ar /><justify><br /> <input type=text name=q size=20 required= /><input value=Buscar type=submit name= /></justify></form> ", 
			"url": "http://dara.aragon.es/opac/app/advanced/",
			"url2": "http://www.elgrado.es/",
			"tipo": [ "1.1 Público", "2.1 Administrativo", "2.2 Histórico", "3.2 Municipal y comarcal" ],
			"provincia": [ "Huesca" ],
			"comarca": [ "Somontano de Barbastro" ],
			"localidad": [ "El Grado/Lo Grau" ],
            "epoca": [ "1789- Contemporánea"],
			"recursos": [ "Documentos" ]			
        },
       {   "id": "Ayuntamiento de El Grado/Lo Grau",
            "birthLatLng": "42.1525533,0.2218722"
        },
{   "label": "Ayuntamiento de Estadilla",
            "type": "Archivos",
             "index": 35,
             "imageURL": "./ESTADlogo.jpg",
			"imageURL2": "./ESTADlogo2.jpg",
            "texto": " <form action=http://dara.aragon.es/opac/app/results/ method=get target=_blank><input type=hidden value=28 name=ar /><justify><br /> <input type=text name=q size=20 required= /><input value=Buscar type=submit name= /></justify></form> ", 
			"url": "http://dara.aragon.es/opac/app/advanced/",
			"url2": "http://www.estadilla.es/",
			"tipo": [ "1.1 Público", "2.1 Administrativo", "2.2 Histórico", "3.2 Municipal y comarcal" ],
			"provincia": [ "Huesca" ],
			"comarca": [ "Somontano de Barbastro" ],
			"localidad": [ "Estadilla" ],
            "epoca": [ "1789- Contemporánea"],
			"recursos": [ "Documentos" ]			
        },
       {   "id": "Ayuntamiento de Estadilla",
            "birthLatLng": "42.0573193,0.2441004"
        },
{   "label": "Ayuntamiento de Fraga",
            "type": "Archivos",
             "index": 36,
             "imageURL": "./FRAGAlogo.jpg",
			"imageURL2": "./FRAGAlogo2.jpg",
            "texto": " <form action=http://dara.aragon.es/opac/app/results/ method=get target=_blank><input type=hidden value=47 name=ar /><justify><br /> <input type=text name=q size=20 required= /><input value=Buscar type=submit name= /></justify></form> ", 
			"url": "http://dara.aragon.es/opac/app/advanced/",
			"url2": "http://www.fraga.org/",
			"tipo": [ "1.1 Público", "2.1 Administrativo", "2.2 Histórico", "3.2 Municipal y comarcal" ],
			"provincia": [ "Huesca" ],
			"comarca": [ "Bajo Cinca / Baix Cinca" ],
			"localidad": [ "Fraga" ],
            "epoca": [ "1789- Contemporánea"],
			"recursos": [ "Documentos" ]			
        },
       {   "id": "Ayuntamiento de Fraga",
            "birthLatLng": "41.5211839,0.3521634"
        },
{   "label": "Ayuntamiento de Fuentespalda",
            "type": "Archivos",
             "index": 37,
             "imageURL": "./FUENTElogo.jpg",
			"imageURL2": "./FUENTElogo.jpg",
            "texto": " <form action=http://dara.aragon.es/opac/app/results/ method=get target=_blank><input type=hidden value=27 name=ar /><justify><br /> <input type=text name=q size=20 required= /><input value=Buscar type=submit name= /></justify></form> ", 
			"url": "http://dara.aragon.es/opac/app/advanced/",
			"url2": "http://www.fuentespalda.es/",
			"tipo": [ "1.1 Público", "2.1 Administrativo", "2.2 Histórico", "3.2 Municipal y comarcal" ],
			"provincia": [ "Teruel" ],
			"comarca": [ "Matarraña / Matarranya" ],
			"localidad": [ "Fuentespalda" ],
            "epoca": [ "1492-1789 Edad Moderna", "1789- Contemporánea"],
			"recursos": [ "Documentos" ]			
        },
       {   "id": "Ayuntamiento de Fuentespalda",
            "birthLatLng": "40.8069553,0.0642614"
        },
{   "label": "Ayuntamiento de Graus",
            "type": "Archivos",
             "index": 38,
             "imageURL": "./GRAUSlogo.jpg",
			"imageURL2": "./GRAUSlogo2.jpg",
            "texto": " <form action=http://dara.aragon.es/opac/app/results/ method=get target=_blank><input type=hidden value=39 name=ar /><justify><br /> <input type=text name=q size=20 required= /><input value=Buscar type=submit name= /></justify></form> ", 
			"url": "http://dara.aragon.es/opac/app/advanced/",
			"url2": "http://www.graus.es/",
			"tipo": [ "1.1 Público", "2.1 Administrativo", "2.2 Histórico", "3.2 Municipal y comarcal" ],
			"provincia": [ "Huesca" ],
			"comarca": [ "La Ribagorza" ],
			"localidad": [ "Graus" ],
            "epoca": [ "1789- Contemporánea"],
			"recursos": [ "Documentos" ]			
        },
       {   "id": "Ayuntamiento de Graus",
            "birthLatLng": "42.189538,0.3364317"
        },
		{   "label": "Ayuntamiento de Huesca",
            "type": "Archivos",
             "index": 39,
             "imageURL": "./HUESCAlogo.jpg",
			"imageURL2": "./HUESCAlogo2.jpg",
            "texto": " <form action=http://dara.aragon.es/opac/app/results/ method=get target=_blank><input type=hidden value=57 name=ar /><justify><br /> <input type=text name=q size=20 required= /><input value=Buscar type=submit name= /></justify></form> ", 
			"url": "http://dara.aragon.es/opac/app/advanced/",
			"url2": "http://www.huesca.es",
			"tipo": [  "1.1 Público", "2.1 Administrativo", "2.2 Histórico", "3.2 Municipal y comarcal" ],
			"provincia": [ "Huesca" ],
			"comarca": [ "Hoya de Huesca / Plana de Huesca" ],
			"localidad": [ "Huesca" ],
            "epoca": [ "0409-1492 Edad Media", "1492-1789 Edad Moderna", "1936-1939 Guerra Civil", "1789- Contemporánea" ],
			"recursos": [ "Documentos", "Fotografías", "Pergaminos", "Mapas y planos", "Audiovisuales", "Carteles" ]			
        },
       {   "id": "Ayuntamiento de Huesca",
            "birthLatLng": "42.140594, -0.408900"
        },
{   "label": "Ayuntamiento de Isábena",
            "type": "Archivos",
             "index": 40,
             "imageURL": "./ISABlogo.jpg",
			"imageURL2": "./ISABlogo.jpg",
            "texto": " <form action=http://dara.aragon.es/opac/app/results/ method=get target=_blank><input type=hidden value=41 name=ar /><justify><br /> <input type=text name=q size=20 required= /><input value=Buscar type=submit name= /></justify></form> ", 
			"url": "http://dara.aragon.es/opac/app/advanced/",
			"url2": "http://www.isabena.es/",
			"tipo": [ "1.1 Público", "2.1 Administrativo", "2.2 Histórico", "3.2 Municipal y comarcal" ],
			"provincia": [ "Huesca" ],
			"comarca": [ "La Ribagorza" ],
			"localidad": [ "Isábena" ],
            "epoca": [ "1789- Contemporánea"],
			"recursos": [ "Documentos" ]			
        },
       {   "id": "Ayuntamiento de Isábena",
            "birthLatLng": "42.3037423,0.542564"
        },
{   "label": "Ayuntamiento de La Almunia de Doña Godina",
            "type": "Archivos",
             "index": 41,
             "imageURL": "./ALMUNlogo.jpg",
			"imageURL2": "./ALMUNlogo2.jpg",
            "texto": " <form action=http://dara.aragon.es/opac/app/results/ method=get target=_blank><input type=hidden value=50 name=ar /><justify><br /> <input type=text name=q size=20 required= /><input value=Buscar type=submit name= /></justify></form> ", 
			"url": "http://dara.aragon.es/opac/app/advanced/",
			"url2": "http://www.laalmunia.es/",
			"tipo": [ "1.1 Público", "2.1 Administrativo", "2.2 Histórico", "3.2 Municipal y comarcal" ],
			"provincia": [ "Zaragoza" ],
			"comarca": [ "Valdejalón" ],
			"localidad": [ "La Almunia de Doña Godina" ],
            "epoca": [ "1789- Contemporánea"],
			"recursos": [ "Documentos" ]			
        },
       {   "id": "Ayuntamiento de La Almunia de Doña Godina",
            "birthLatLng": "41.4779252,-1.3733124"
        },
{   "label": "Ayuntamiento de La Fresneda",
            "type": "Archivos",
             "index": 42,
             "imageURL": "./FRESNlogo.jpg",
			"imageURL2": "./FRESNlogo2.jpg",
            "texto": " <form action=http://dara.aragon.es/opac/app/results/ method=get target=_blank><input type=hidden value=40 name=ar /><justify><br /> <input type=text name=q size=20 required= /><input value=Buscar type=submit name= /></justify></form> ", 
			"url": "http://dara.aragon.es/opac/app/advanced/",
			"url2": "http://www.lafresneda.gob.es/",
			"tipo": [ "1.1 Público", "2.1 Administrativo", "2.2 Histórico", "3.2 Municipal y comarcal" ],
			"provincia": [ "Teruel" ],
			"comarca": [ "Matarraña / Matarranya" ],
			"localidad": [ "La Fresneda" ],
            "epoca": [ "1492-1789 Edad Moderna", "1789- Contemporánea"],
			"recursos": [ "Documentos" ]			
        },
       {   "id": "Ayuntamiento de La Fresneda",
            "birthLatLng": "40.9285409,0.074616"
        },
{   "label": "Ayuntamiento de Mequinenza",
            "type": "Archivos",
             "index": 43,
             "imageURL": "./MEQUIlogo.jpg",
			"imageURL2": "./MEQUIlogo2.jpg",
            "texto": " <form action=http://dara.aragon.es/opac/app/results/ method=get target=_blank><input type=hidden value=36 name=ar /><justify><br /> <input type=text name=q size=20 required= /><input value=Buscar type=submit name= /></justify></form> ", 
			"url": "http://dara.aragon.es/opac/app/advanced/",
			"url2": "http://www.mequinenza.com/",
			"tipo": [ "1.1 Público", "2.1 Administrativo", "2.2 Histórico", "3.2 Municipal y comarcal" ],
			"provincia": [ "Zaragoza" ],
			"comarca": [ "Bajo Cinca / Baix Cinca" ],
			"localidad": [ "Mequinenza" ],
            "epoca": [ "1789- Contemporánea"],
			"recursos": [ "Documentos" ]			
        },
       {   "id": "Ayuntamiento de Mequinenza",
            "birthLatLng": "41.374164,0.3023665"
        },
{   "label": "Ayuntamiento de Molinos",
            "type": "Archivos",
             "index": 44,
             "imageURL": "./MOLIlogo.jpg",
			"imageURL2": "./MOLIlogo.jpg",
            "texto": " <form action=http://dara.aragon.es/opac/app/results/ method=get target=_blank><input type=hidden value=62 name=ar /><justify><br /> <input type=text name=q size=20 required= /><input value=Buscar type=submit name= /></justify></form> ", 
			"url": "http://dara.aragon.es/opac/app/advanced/",
			"url2": "http://www.molinos.es",
			"tipo": [ "1.1 Público", "2.1 Administrativo", "3.2 Municipal y comarcal" ],
			"provincia": [ "Teruel" ],
			"comarca": [ "Maestrazgo" ],
			"localidad": [ "Molinos" ],
            "epoca": ["1789- Contemporánea"],
			"recursos": [ "Documentos"]			
        },
       {   "id": "Ayuntamiento de Molinos",
            "birthLatLng": "40.8197474,-0.4499543"
        },
{   "label": "Ayuntamiento de Naval",
            "type": "Archivos",
             "index": 45,
             "imageURL": "./SOMO5logo.jpg",
			"imageURL2": "./NAVAlogo2.jpg",
            "texto": " <form action=http://dara.aragon.es/opac/app/results/ method=get target=_blank><input type=hidden value=29 name=ar /><justify><br /> <input type=text name=q size=20 required= /><input value=Buscar type=submit name= /></justify></form> ", 
			"url": "http://dara.aragon.es/opac/app/advanced/",
			"url2": "http://www.naval.es/",
			"tipo": [ "1.1 Público", "2.1 Administrativo", "2.2 Histórico", "3.2 Municipal y comarcal" ],
			"provincia": [ "Huesca" ],
			"comarca": [ "Somontano de Barbastro" ],
			"localidad": [ "Naval" ],
            "epoca": [ "1789- Contemporánea"],
			"recursos": [ "Documentos" ]			
        },
       {   "id": "Ayuntamiento de Naval",
            "birthLatLng": "42.1922426,0.1531304"
        },
{   "label": "Ayuntamiento de Peralta de Alcofea",
            "type": "Archivos",
             "index": 46,
             "imageURL": "./PERALlogo.jpg",
			"imageURL2": "./PERALlogo2.jpg",
            "texto": " <form action=http://dara.aragon.es/opac/app/results/ method=get target=_blank><input type=hidden value=31 name=ar /><justify><br /> <input type=text name=q size=20 required= /><input value=Buscar type=submit name= /></justify></form> ", 
			"url": "http://dara.aragon.es/opac/app/advanced/",
			"url2": "http://www.peraltadealcofea.es/",
			"tipo": [ "1.1 Público", "2.1 Administrativo", "2.2 Histórico", "3.2 Municipal y comarcal" ],
			"provincia": [ "Huesca" ],
			"comarca": [ "Somontano de Barbastro" ],
			"localidad": [ "Peralta de Alcofea" ],
            "epoca": [ "1789- Contemporánea"],
			"recursos": [ "Documentos" ]			
        },
       {   "id": "Ayuntamiento de Peralta de Alcofea",
            "birthLatLng": "41.9311465,-0.0668648"
        },
{   "label": "Ayuntamiento de Peralta de Calasanz",
            "type": "Archivos",
             "index": 47,
             "imageURL": "./PERAL2logo.jpg",
			"imageURL2": "./PERAL2logo2.jpg",
            "texto": " <form action=http://dara.aragon.es/opac/app/results/ method=get target=_blank><input type=hidden value=25 name=ar /><justify><br /> <input type=text name=q size=20 required= /><input value=Buscar type=submit name= /></justify></form> ", 
			"url": "http://dara.aragon.es/opac/app/advanced/",
			"url2": "http://www.peraltadecalasanz.es/",
			"tipo": [ "1.1 Público", "2.1 Administrativo", "2.2 Histórico", "3.2 Municipal y comarcal" ],
			"provincia": [ "Huesca" ],
			"comarca": [ "La Litera / La Llitera" ],
			"localidad": [ "Peralta de Calasanz" ],
            "epoca": [ "1789- Contemporánea"],
			"recursos": [ "Documentos" ]			
        },
       {   "id": "Ayuntamiento de Peralta de Calasanz",
            "birthLatLng": "41.9924862,0.3859629"
        },
{   "label": "Ayuntamiento de Sadaba",
            "type": "Archivos",
             "index": 48,
             "imageURL": "./SADABlogo.jpg",
			"imageURL2": "./SADABlogo2.jpg",
            "texto": " <form action=http://dara.aragon.es/opac/app/results/ method=get target=_blank><input type=hidden value=26 name=ar /><justify><br /> <input type=text name=q size=20 required= /><input value=Buscar type=submit name= /></justify></form> ", 
			"url": "http://dara.aragon.es/opac/app/advanced/",
			"url2": "http://www.sadaba.es/",
			"tipo": [ "1.1 Público", "2.1 Administrativo", "2.2 Histórico", "3.2 Municipal y comarcal" ],
			"provincia": [ "Zaragoza" ],
			"comarca": [ "Cinco Villas" ],
			"localidad": [ "Sadaba" ],
            "epoca": [ "1789- Contemporánea"],
			"recursos": [ "Documentos" ]			
        },
       {   "id": "Ayuntamiento de Sadaba",
            "birthLatLng": "42.2819073,-1.274292"
        },
{   "label": "Ayuntamiento de Salas Altas",
            "type": "Archivos",
             "index": 49,
             "imageURL": "./SALASlogo.jpg",
			"imageURL2": "./SALASlogo2.jpg",
            "texto": " <form action=http://dara.aragon.es/opac/app/results/ method=get target=_blank><input type=hidden value=32 name=ar /><justify><br /> <input type=text name=q size=20 required= /><input value=Buscar type=submit name= /></justify></form> ", 
			"url": "http://dara.aragon.es/opac/app/advanced/",
			"url2": "http://www.salasaltas.es/",
			"tipo": [ "1.1 Público", "2.1 Administrativo", "2.2 Histórico", "3.2 Municipal y comarcal" ],
			"provincia": [ "Huesca" ],
			"comarca": [ "Somontano de Barbastro" ],
			"localidad": [ "Salas Altas" ],
            "epoca": [ "1789- Contemporánea"],
			"recursos": [ "Documentos" ]			
        },
       {   "id": "Ayuntamiento de Salas Altas",
            "birthLatLng": "42.1147056,0.0714853"
        },
       {   "id": "Ayuntamiento de Peralta de Alcofea",
            "birthLatLng": "41.9311465,-0.0668648"
        },
{   "label": "Ayuntamiento de Tamarite de Litera",
            "type": "Archivos",
             "index": 50,
             "imageURL": "./TAMAlogo.jpg",
			"imageURL2": "./TAMAlogo.jpg",
            "texto": " <form action=http://dara.aragon.es/opac/app/results/ method=get target=_blank><input type=hidden value=56 name=ar /><justify><br /> <input type=text name=q size=20 required= /><input value=Buscar type=submit name= /></justify></form> ", 
			"url": "http://dara.aragon.es/opac/app/advanced/",
			"url2": "http://www.tamaritedelitera.es/",
			"tipo": [ "1.1 Público", "2.1 Administrativo", "2.2 Histórico", "3.2 Municipal y comarcal" ],
			"provincia": [ "Huesca" ],
			"comarca": [ "La Litera / La Llitera" ],
			"localidad": [ "Tamarite de Litera" ],
            "epoca": [ "1789- Contemporánea"],
			"recursos": [ "Documentos" ]			
        },
       {   "id": "Ayuntamiento de Tamarite de Litera",
            "birthLatLng": "41.8690257,0.4218037"
        },
{   "label": "Ayuntamiento de Tarazona",
            "type": "Archivos",
             "index": 51,
             "imageURL": "./TARAlogo.jpg",
			"imageURL2": "./TARAlogo.jpg",
            "texto": " <form action=http://dara.aragon.es/opac/app/results/ method=get target=_blank><input type=hidden value=55 name=ar /><justify><br /> <input type=text name=q size=20 required= /><input value=Buscar type=submit name= /></justify></form> ", 
			"url": "http://dara.aragon.es/opac/app/advanced/",
			"url2": "http://www.tarazona.es/",
			"tipo": [ "1.1 Público", "2.1 Administrativo", "2.2 Histórico", "3.2 Municipal y comarcal" ],
			"provincia": [ "Zaragoza" ],
			"comarca": [ "Tarazona y el Moncayo" ],
			"localidad": [ "Tarazona" ],
            "epoca": [ "1789- Contemporánea"],
			"recursos": [ "Documentos" ]			
        },
       {   "id": "Ayuntamiento de Tarazona",
            "birthLatLng": "41.9048809,-1.7262283"
        },
{   "label": "Ayuntamiento de Tronchón",
            "type": "Archivos",
             "index": 52,
             "imageURL": "./TRONlogo.jpg",
			"imageURL2": "./TRONlogo.jpg",
            "texto": " <form action=http://dara.aragon.es/opac/app/results/ method=get target=_blank><input type=hidden value=63 name=ar /><justify><br /> <input type=text name=q size=20 required= /><input value=Buscar type=submit name= /></justify></form> ", 
			"url": "http://dara.aragon.es/opac/app/advanced/",
			"url2": "https://236ws.dpteruel.es/tramitar/tronchon/ciudadanos",
			"tipo": [ "1.1 Público", "2.1 Administrativo", "2.2 Histórico", "3.2 Municipal y comarcal" ],
			"provincia": [ "Teruel" ],
			"comarca": [ "Maestrazgo" ],
			"localidad": [ "Tronchón" ],
            "epoca": [ "1789- Contemporánea"],
			"recursos": [ "Documentos" ]			
        },
       {   "id": "Ayuntamiento de Tronchón",
            "birthLatLng": "40.6206732,-0.3981608"
        },
	{   "label": "Ayuntamiento de Zaragoza",
            "type": "Archivos",
             "index": 53,
             "imageURL": "./ZARAlogo.jpg",
			"imageURL2": "./ZARAlogo2.jpg",
            "texto": " <form action=http://dara.aragon.es/opac/app/results/ method=get target=_blank><input type=hidden value=24 name=ar /><justify><br /> <input type=text name=q size=20 required= /><input value=Buscar type=submit name= /></justify></form> ", 
			"url": "http://dara.aragon.es/opac/app/advanced/",
			"url2": "http://www.zaragoza.es/ciudad/usic/",
			"tipo": [ "1.1 Público", "2.1 Administrativo", "2.2 Histórico", "3.2 Municipal y comarcal" ],
			"provincia": [ "Zaragoza" ],
			"comarca": [ "Zaragoza" ],
			"localidad": [ "Zaragoza" ],
             "epoca": [ "0409-1492 Edad Media", "1492-1789 Edad Moderna", "1789- Contemporánea", "1936-1939 Guerra Civil", "1975-1982 Transición", "1978- Democracia", "1982- Autonomía de Aragón" ],
			"recursos": [ "Documentos", "Fotografías", "Pergaminos", "Mapas y planos",  "Audiovisuales",  "Carteles" ]				
        },
       {   "id": "Ayuntamiento de Zaragoza",
            "birthLatLng": "41.635326, -0.911173"
        },
{   "label": "Cabildo Catedral de Huesca",
            "type": "Archivos",
             "index": 54,
             "imageURL": "./CATHlogo.jpg",
			"imageURL2": "./CATHlogo.jpg",
            "texto": " <form action=http://dara.aragon.es/opac/app/results/ method=get target=_blank><input type=hidden value=43 name=ar /><justify><br /> <input type=text name=q size=20 required= /><input value=Buscar type=submit name= /></justify></form> ", 
			"url": "http://dara.aragon.es/opac/app/advanced/",
			"url2": "http://www.diocesisdehuesca.org/",
			"tipo": [ "1.2 Privado", "2.2 Histórico", "4.1 Religioso" ],
			"provincia": [ "Huesca" ],
			"comarca": [ "Hoya de Huesca / Plana de Huesca" ],
			"localidad": [ "Huesca" ],
            "epoca": [ "0409-1492 Edad Media", "1492-1789 Edad Moderna", "1789- Contemporánea"],
			"recursos": [ "Documentos", "Pergaminos" ]			
        },
       {   "id": "Cabildo Catedral de Huesca",
            "birthLatLng": "42.140611, -0.408307"
        },
{   "label": "Archivo Barones de Valdeolivos de Fonz",
            "type": "Archivos",
             "index": 55,
             "imageURL": "./VFONlogo.jpg",
			"imageURL2": "./VFONlogo.jpg",
            "texto": " <form action=http://dara.aragon.es/opac/app/results/ method=get target=_blank><input type=hidden value=7 name=ar /><justify><br /> <input type=text name=q size=20 required= /><input value=Buscar type=submit name= /></justify></form> ", 
			"url": "http://dara.aragon.es/opac/app/advanced/crbv",
			"url2": "http://www.patrimonioculturaldearagon.es/bienes-culturales/casa-ric-palacio-de-los-barones-de-valdeolivos-fonz",
			"tipo": [ "1.2 Privado", "2.2 Histórico", "4.3 Nobiliario" ],
			"provincia": [ "Huesca" ],
			"comarca": [ "Cinca Medio" ],
			"localidad": [ "Fonz" ],
            "epoca": [ "0409-1492 Edad Media", "1492-1789 Edad Moderna", "1789- Contemporánea"],
			"recursos": [ "Documentos" ]			
        },
       {   "id": "Archivo Barones de Valdeolivos de Fonz",
            "birthLatLng": "42.0111247,0.2591816"
        },
{   "label": "Comunidad de Albarracín",
            "type": "Archivos",
             "index": 56,
             "imageURL": "./ALDElogo.jpg",
			"imageURL2": "./ALDElogo2.jpg",
            "texto": " <form action=http://dara.aragon.es/opac/app/results/ method=get target=_blank><input type=hidden value=52 name=ar /><justify><br /> <input type=text name=q size=20 required= /><input value=Buscar type=submit name= /></justify></form> ", 
			"url": "http://dara.aragon.es/opac/app/advanced/",
			"url2": "http://comunidaddealbarracin.org/",
			"tipo": [ "1.1 Público", "2.1 Administrativo", "2.2 Histórico", "3.2 Municipal y comarcal" ],
			"provincia": [ "Teruel" ],
			"comarca": [ "Sierra de Albarracín" ],
			"localidad": [ "Tramacastilla" ],
            "epoca": [ "0409-1492 Edad Media", "1492-1789 Edad Moderna", "1789- Contemporánea"],
			"recursos": [ "Documentos", "Pergaminos" ]			
        },
       {   "id": "Comunidad de Albarracín",
            "birthLatLng": "40.430329,-1.5725979"
        },
{   "label": "Comunidad de Teruel",
            "type": "Archivos",
             "index": 57,
             "imageURL": "./MOSQUElogo.jpg",
			"imageURL2": "./MOSQUElogo.jpg",
            "texto": " <form action=http://dara.aragon.es/opac/app/results/ method=get target=_blank><input type=hidden value=58 name=ar /><justify><br /> <input type=text name=q size=20 required= /><input value=Buscar type=submit name= /></justify></form> ", 
			"url": "http://dara.aragon.es/opac/app/advanced/",
			"url2": "http://dara.aragon.es/opac/doma/archivo-ComunidadTeruel.jsp",
			"tipo": [ "1.1 Público", "2.1 Administrativo", "2.2 Histórico", "3.2 Municipal y comarcal" ],
			"provincia": [ "Teruel" ],
			"comarca": [ "Gudar-Javalambre" ],
			"localidad": [ "Mosqueruela" ],
            "epoca": [ "0409-1492 Edad Media", "1492-1789 Edad Moderna", "1789- Contemporánea"],
			"recursos": [ "Documentos", "Pergaminos" ]			
        },
       {   "id": "Comunidad de Teruel",
            "birthLatLng": "40.361466,-0.448891"
        },
		{   "label": "Diputación Provincial de Huesca",
            "type": "Archivos",
             "index": 58,
             "imageURL": "./DPHlogo.jpg",
			"imageURL2": "./DPHlogo.jpg",
            "texto": " <form action=http://dara.aragon.es/opac/app/results/adph method=get target=_blank><input type=hidden /><justify><br /> <input type=text name=q size=20 required= /><input value=Buscar type=submit name= /></justify></form>  ", 
			"url": "http://dara.aragon.es/opac/app/advanced/adph",
			"url2": "http://www.dphuesca.es/index.php/mod.pags/mem.detalle/idpag.114/idmenu.66/chk.ab975c547fb9ed6f1a65397f8095106e.html",
			"tipo": [  "1.1 Público", "2.2 Histórico", "3.3 Provincial" ],
			"provincia": [ "Huesca" ],
			"comarca": [ "Hoya de Huesca / Plana de Huesca" ],
			"localidad": [ "Huesca" ],
            "epoca": [ "1492-1789 Edad Moderna", "1936-1939 Guerra Civil", "1789- Contemporánea", "1975-1982 Transición", "1978- Democracia"],
			"recursos": [ "Documentos", "Fotografías", "Mapas y planos", "Audiovisuales", "Carteles" ]			
        },
       {   "id": "Diputación Provincial de Huesca",
            "birthLatLng": "42.136776, -0.408384"
        },
		{   "label": "Fototeca de la Diputación Provincial de Huesca",
            "type": "Archivos",
             "index": 59,
             "imageURL": "./FDPHlogo.jpg",
			"imageURL2": "./FDPHlogo.jpg",
            "texto": " <form action=http://dara.aragon.es/opac/app/results/ method=get target=_blank><input type=hidden value=5 name=ar /><justify><br /> <input type=text name=q size=20 required= /><input value=Buscar type=submit name= /></justify></form> ", 
			"url": "http://dara.aragon.es/opac/app/advanced/",
			"url2": "http://www.dphuesca.es/index.php/mod.pags/mem.detalle/idpag.610/idmenu.1072/chk.3c88daf2802add6535a37c49ad68fdfb.html",
			"tipo": [  "1.1 Público", "2.2 Histórico", "3.3 Provincial" ],
			"provincia": [ "Huesca" ],
			"comarca": [ "Hoya de Huesca / Plana de Huesca" ],
			"localidad": [ "Huesca" ],
            "epoca": [ "1789- Contemporánea" ],
			"recursos": [ "Documentos", "Fotografías", "Mapas y planos", "Audiovisuales", "Carteles" ]			
        },
       {   "id": "Fototeca de la Diputación Provincial de Huesca",
            "birthLatLng": "42.140779, -0.398297"
        },
		{   "label": "Diputación Provincial de Zaragoza",
            "type": "Archivos",
             "index": 60,
             "imageURL": "./DPZlogo.jpg",
			"imageURL2": "./DPZlogo2.jpg",
            "texto": " <form action=http://dara.aragon.es/opac/app/results/adpz method=get target=_blank><input type=hidden /><justify><br /> <input type=text name=q size=20 required= /><input value=Buscar type=submit name= /></justify></form>  ", 
			"url": "http://dara.aragon.es/opac/app/advanced/adpz",
			"url2": "http://cultura.dpz.es/es/archivos-y-bibliotecas/id/51",
			"tipo": [  "1.1 Público", "2.2 Histórico", "3.3 Provincial" ],
			"provincia": [ "Zaragoza" ],
			"comarca": [ "Zaragoza" ],
			"localidad": [ "Zaragoza" ],
            "epoca": [ "1492-1789 Edad Moderna", "1936-1939 Guerra Civil", "1789- Contemporánea", "1975-1982 Transición", "1978- Democracia"],
			"recursos": [ "Documentos", "Fotografías", "Mapas y planos", "Audiovisuales", "Carteles" ]			
        },
       {   "id": "Diputación Provincial de Zaragoza",
            "birthLatLng": "41.652224, -0.881626"
        },
{   "label": "Escuelas Pías de Aragón",
            "type": "Archivos",
             "index": 61,
             "imageURL": "./ESCOLlogo.jpg",
			"imageURL2": "./ESCOLlogo2.jpg",
            "texto": " <form action=http://dara.aragon.es/opac/app/results/escp method=get target=_blank><input type=hidden /><justify><br /> <input type=text name=q size=20 required= /><input value=Buscar type=submit name= /></justify></form>  ", 
			"url": "http://dara.aragon.es/opac/app/advanced/escp",
			"url2": "http://www.escuelaspias.zaragoza.escolapiosemaus.org/",
			"tipo": [ "1.2 Privado", "2.2 Histórico", "4.1 Religioso" ],
			"provincia": [ "Zaragoza" ],
			"comarca": [ "Zaragoza" ],
			"localidad": [ "Zaragoza" ],
            "epoca": [ "1789- Contemporánea"],
			"recursos": [ "Pergaminos" ]			
        },
       {   "id": "Escuelas Pías de Aragón",
            "birthLatLng": "41.654548, -0.885405"
        },
{   "label": "Ex-Catedral de Roda de Isábena",
            "type": "Archivos",
             "index": 62,
             "imageURL": "./RODAlogo.jpg",
			"imageURL2": "./RODAlogo.jpg",
            "texto": " <form action=http://dara.aragon.es/opac/app/results/ method=get target=_blank><input type=hidden value=44 name=ar /><justify><br /> <input type=text name=q size=20 required= /><input value=Buscar type=submit name= /></justify></form> ", 
			"url": "http://dara.aragon.es/opac/app/advanced/",
			"url2": "http://www.diocesisbarbastromonzon.org",
			"tipo": [ "1.2 Privado", "2.2 Histórico", "4.1 Religioso" ],
			"provincia": [ "Huesca" ],
			"comarca": [ "Somontano de Barbastro" ],
			"localidad": [ "Roda de Isábena" ],
            "epoca": [ "0409-1492 Edad Media" ],
			"recursos": [ "Pergaminos" ]			
        },
       {   "id": "Ex-Catedral de Roda de Isábena",
            "birthLatLng": "42.2912603,0.5286223"
        },
	{   "label": "Fundación Hospital de Benasque",
            "type": "Archivos",
             "index": 63,
             "imageURL": "./FHBlogo.jpg",
			"imageURL2": "./FHBlogo2.jpg",
            "texto": " <form action=http://dara.aragon.es/opac/app/results/afhb method=get target=_blank><input type=hidden /><justify><br /> <input type=text name=q size=20 required= /><input value=Buscar type=submit name= /></justify></form>  ", 
			"url": "http://dara.aragon.es/opac/app/advanced/afhb",
			"url2": "http://www.fundacion-hospital-benasque.org/",
			"tipo": [ "1.2 Privado", "2.2 Histórico", "4.2 Etnográfico" ],
			"provincia": [ "Huesca" ],
			"comarca": [ "La Ribagorza" ],
			"localidad": [ "Benasque" ],
            "epoca": [ "1492-1789 Edad Moderna", "1789- Contemporánea" ],
			"recursos": [ "Documentos", "Fotografías" ]			
        },
       {   "id": "Fundación Hospital de Benasque",
            "birthLatLng": "42.6010311,0.5092045"
        }
		]
}
